### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by bowlofeggs** [Pylons/pylons-sphinx-themes#8]
Hello!

I'm interested in packaging this theme for Fedora, but I've noticed a slight licensing confusion that I think would be good to get some clarification on. The [LICENSE.txt](https://github.com/Pylons/pylons-sphinx-themes/blob/1.0.4/LICENSE.txt) says this package is licensed CC-BY-SA, but the [setup.py](https://github.com/Pylons/pylons-sphinx-themes/blob/1.0.4/setup.py) says it's "BSD-derived" in one place, and says "Repoze Public License" in the classifiers.

I presume the CC-BY-SA applies to the static content and the Repoze license applies to the Python code, but it would be good to clarify this (especially if my presumption is not correct).

A specific proposal:

* Modify the LICENSE.txt to specify that the static content is CC-BY-SA.
* Modify the LICENSE.txt to specify that the Python code is Repoze.
* Modify the setup.py to list both licenses, since both sets of artifacts get shipped.

Maybe also nice to do:

* Add a license header to the 3 Python files (setup.py, __init__.py, and pylons_theme_support.py) that documents the Repoze license.

Note also that Repoze is not in Fedora's current list of approved licenses, so I would also need to get Fedora's legal SIG to review the license for approval:

https://fedoraproject.org/wiki/Licensing:Main

I don't anticipate a problem with that, but I am also not a lawyer.

**Comment by digitalresistor** [comment]
Why exactly are you packaging this repository? This is used to build our docs, I don't understand why anyone would want this to live in a package repository...

----

The license is the repoze license as specified in `setup.py`:

https://github.com/Pylons/pylons-sphinx-themes/blob/master/setup.py#L56

I'll update this repo with that license in a second, `CC-BY-SA` doesn't make sense for this repo, since it is mostly code that is used by Sphinx to generate a static site. Static content generated with this theme is under whatever license the repository that uses is licensing the docs under. This differs for the different Pylons projects.

Since you are already packaging other Pylons projects that use the Repoze license, I assume there won't be any issues with Fedora's Legal SIG. (See: Pyramid, Colander, pyramid_tm, pyramid_*)

**Comment by stevepiercy** [comment]
Thanks for the report. See the licensing as explained in [License Terms](https://github.com/Pylons/pylons-sphinx-themes/blob/master/CONTRIBUTORS.txt#L46) and [Licensing Exceptions](https://github.com/Pylons/pylons-sphinx-themes/blob/master/CONTRIBUTORS.txt#L88).

**Comment by bowlofeggs** [comment]
Hi @bertjwregeer!

I'm also the packager for plaster, and I had to patch it to not use this theme so its docs would build:

https://src.fedoraproject.org/rpms/python-plaster/blob/master/f/python-plaster.spec#_79

My motivation is to package these themes for Fedora so they can become a build dependency for plaster and so that plaster can have the theme as intended. It's not really a strict requirement, because there's not a real problem today, per se.

I didn't realize that Pyramid was also Repoze. Thanks for the info there.

**Comment by stevepiercy** [comment]
@bowlofeggs we're hashing out some details to make licensing consistent and correct in [#pyramid on IRC](https://botbot.me/freenode/pyramid/). Resolution shortly.

**Comment by digitalresistor** [comment]
This was resolved with #9.

**Comment by bowlofeggs** [comment]
Just in case anyone is interested, this package is in Fedora's Rawhide release now:

https://bugzilla.redhat.com/show_bug.cgi?id=1497330

It should end up in Fedora 25, 26, and 27 later this week. Thanks for the help!
